### ISSUE TITLE
[bug] PHP Notice:  Undefined variable: output in /var/www/html/oc/admin/controller/extension/payment/paypal_plus.php on line 286

### ISSUE THREAD

**Issue by marcelowu** [br-paypaldev/opencart-module#1]
**Qual versão do OpenCart você está utilizando?**
3.0.3.6

**Que parte da loja é afetada pelo erro?**
nao habilita

**Faça um resumo do problema ocasionado pelo erro:**
 PHP Notice:  Undefined variable: output in /var/www/html/oc/admin/controller/extension/payment/paypal_plus.php on line 286

 - Você está em localhost ou servidor de hospedagem?
 localhost

 - Qual o sistema operacional utilizado?
ubuntu 20.04
 
 - Qual o servidor web utilizado?
Nginx
 
 - Qual a versão do PHP?
7.3

**Comment by v5mvidal** [comment]
**Resolvido!**

Baixe novamente a extensão PayPal Plus compatível com sua versão do OpenCart no link abaixo:
https://github.com/br-paypaldev/opencart-module/tree/master/dist

E atualize em sua loja, sendo que após a atualização, acesse as configurações da extensão **PayPal Plus** e clique no botão **Salvar**.

**Comment by marcelowu** [comment]
nao mostra nada em sandbox?

![Captura de tela de 2020-11-29 02-56-56](https://user-images.githubusercontent.com/30912144/100534536-beeb4800-31ee-11eb-9ba9-14c7ddaf9de3.png)

**Comment by v5mvidal** [comment]
Mostra sim, mas como você está testando em ambiente local, sem o https e aparentemente utilizando um checkout diferente do checkout padrão do OpenCart, não tem como saber:

- Se você está habilitado para utilizar o PayPal Plus.
- Como você configurou a extensão PayPal Plus.
- Como funciona o checkout da sua loja, para sabermos se algum ajuste deve ser realizado.

Neste caso, entre em contato com o PayPal pelo número **0800 047 4482**, para dúvidas relacionadas a habilitação do PayPal Plus.

E caso necessite de acompanhamento em seus testes, acesse o portal de suporte técnico e abra um ticket detalhando o seu problema na seção "**Fale Conosco**":
[https://www.paypal-support.com/s/?language=pt_BR](https://www.paypal-support.com/s/?language=pt_BR)
